version: '3.8'
services:
  nginx:
    build: ./nginx-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
  backend:
    build: ./backend-java-springboot
    # ports:
    #   - "8080:8080"
  frontend:
    build: ./frontend-react
    # ports:
    #   - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    driver: bridge