version: '3.8'
services:
  backend:
    build: ./backend-java-springboot
    ports:
      - "8080:8080"
  frontend:
    build: ./frontend-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
